language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
matrix:
  fast_finish: true
compiler:
  - clang
  - gcc
before_script:
  - bundle update
  - bundle exec rake clobber
  - ruby -v
